# -*- coding: utf-8 -*-
"""Copy of EXPERIMENT1_a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a1rJwXjJKkbcrgOKqRXpRxnHJNvkWZdl

<h1 align="center">  Experiment 1.A</h1> 
Date___________________

Aim: To perform a review of python programming

**Basic Data Types**
"""

print("hello World")

a=5
print(a)
print(type(a))

f=1.5
print(f)
print(type(f))

s="hello"
print(s)
print(type(s))

b=True
print(b)
print(type(b))

t=True
f=False
print(t,f)

t=5+3j
print(t)
print(type(t))

"""**ARITHMETIC OPERATORS**"""

a=7
b=3
sum=a+b
print(sum)

diff=a-b
print(diff)

pro=a*b
print(pro)

quo=a/b
print(quo)

iquo=a//b
print(iquo)

rem=a % b
print(rem)

pow= a**b
print(pow)

"""**BOOLEAN OPERATIONS**"""

t=True
f=False
print(t,f)

p=5>3
print(p)

q=-1<-12.5
print(q)

print(p and q)

print(p or p)

print(not q)

"""**STRING OPERATIONS**"""

s='hello'
u="hello"
print(s)
print(u)

s1="python"
s2='world'
s3=s1+' '+s2
print(s3)

s3='%s %s %d' %(s1,s2,1011)
print(s3)

print(len(s3))

print(s3.upper())

print(s3.capitalize())

print(s3.lower())

print('hello world how are you'.split(' '))

print('book'.replace('o','e'))

word='jewellery'
print(word.find('well'))
print(word.find('is'))

"""**CONTROL STRUCTURES**

IF-ELSE
"""

number= 123
if number>99 and number<1000 :
     print('3 digit')
else:
     print('Not 3 digit')

response=input('Are you familiar with python ')
if response.upper()=="YES":
  print("You can skip this course:-)")
elif response.upper() == "NO":
  print("You are at the right place:-)")
else:
  print('Sorry wrong input :-(')

"""FOR LOOP"""

for x in range(10):
  print(x,end=' ')

limit=int(input('Enter a limit :'))
sum=0
for i in range(1,limit+1):
  if i%2!=0:
    sum+=i
print("Odd sum="+str(sum))

print(list(range(10)))

print(list(range(1,10)))

print(list(range(1,10,2)))

"""WHILE LOOP"""

number=int(input('Enter number :'))
s=0
while number>0:
  s+=number%10
  number=number//10
print(s)

"""NESTED LOOP"""

limit=int(input('Enter number :'))
for num in range (2,limit+1):
  is_divisible=False
  k=2
  while k<=num//2:
    if num % k==0:
      is_divisible=True
      break;
    k+=1
  if not is_divisible:
    print(num,end=' ')

"""**CONTAINERS**

LIST
"""

mylist=['a','b',1,1.2,True]
print(mylist)
mylist.append("new")
print(mylist)

print(mylist.pop())

mylist.insert(2,'new')
print(mylist)

mylist.remove('new')
print(mylist)

b=[1,2,3]
print(b)
mylist.append(b)
print(mylist)

mylist.remove(b)
print(mylist)

mylist.extend(b)
print(mylist)

a=[2,3,1,4,5]
a.sort()
print(a)

print(list('hello'))

"""LIST SLICING"""

numbers=[0,1,2,3,4,5,6,7,8,9,10]
print(numbers[1],numbers[-1])

sliced=numbers[5:11]
print(sliced)

slice1=numbers[5:]
print(slice1)

Sliced=numbers[:7]
print(Sliced)

slice2=numbers[-2:]
print(slice2)

"""LIST COMPREHENSION"""

numbers=list(range(1,8))
print(numbers)

square=[]
for i in numbers:
   square.append(pow(i,2))
print(square)

square=[x**2 for x in numbers]
print(square)

odd_square=[x**2 for x in numbers if x%2!=0]
print(odd_square)

A=[4,6,8,9]
AxA=[(a,b) for a in A for b in A if a!=b ]
print(AxA)

"""DICTIONARY"""

person={'name':'Manu','age':28}
print(person['name'])

print('name' in person)

print('sex' in person)

person['sex']='male'
print(person)

for item in person:
   print(item,person[item])

for(key,value)in person.items():
   print(key.capitalize(),'\t:\t',value)
print(person.keys())

"""**FUNCTIONS**

FINDING THE SQUARE OF A NUMBER
"""

def square(number):
  return pow(number,2)
s=square(5)
print(s)

"""prime in given range"""

def isPrime(number):

    for factor in range(2, (number//2)+1):
        if number%factor == 0:

              return False

    return True

number = int(input('Enter the number '))
print(isPrime(number))

def printPrimes(llimit, ulimit):
  for num in range(llimit,ulimit+1):
    if isPrime(num)==True:
      print(num,end=' ')
printPrimes(5,50)

"""swap 2 numbers"""

def swap(x,y):
  t=x
  x=y
  y=t
  return x,y
a=5
b=7
a,b=swap(a,b)
print(a,b)